export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';

export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL ='REGISTER_FAIL';

export const GET_ERRORS='GET_ERROR';
export const CLEAR_ERRORS='CLEAR_ERROR';

export const FETCH_USER='FETCH_USER';
export const ERROR_RESPONSE='ERROR_RESPONSE';

export const GET_POSTLIST='GET_POSTLIST';
export const GET_PHOTO='GET_PHOTO';
export const COMMENT_SUCCESS='COMMENT_SUCCESS';

export const FOLLOW='FOLLOW';
export const FOLLOWED='FOLLOWED';